name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: cypress install
        uses: cypress-io/github-action@v6
        with:
          install: true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          runTests: true